### ISSUE TITLE
DBT + SQL Grammar

### ISSUE THREAD

**Issue by shruti222patel** [dbt-labs/tree-sitter-jinja2#20]
Hi 👋 

It seems like this grammar is only for the jinja template. Is there a grammar I can use to parse the SQL + jinja dbt model code?

**Comment by shruti222patel** [comment]
One option could be using existing SQL tree-sitter parsers in conjunction with this one, but the dialects they support are limited. :/

**Comment by vergenzt** [comment]
I'm interested in this too! I've been thinking it would be _really_ neat to be able to annotate macros with the SQL syntax node type they return and do some static validation that they're only used in those positions... one can dream 🙂
